### ISSUE TITLE
Não consigo executar o código

### ISSUE THREAD

**Issue by yullidias** [danfcosta/nubankexporter#1]
A senha que tenho que passar pela linha de comando é a do aplicativo de celular do Nubank, certo? O cpf é somente números?

Tentei executar o código e obtive os erros 401 e 403. Sabe o que pode ser?

**Comment by danfcosta** [comment]
Olá Yulli,

CPF é somente número e a senha é a mesma usada na Web (não lembro se é a
mesma do celular).
Não conheço esses erros. No trace aparece alguma informação útil?

Atenciosamente,

*Danilo Freitas da Costa*

**Comment by yullidias** [comment]
Olá Danilo!

Descobri que a senha da WEB é a mesma do app. O problema era os caracteres especiais da minha senha. Eu uso o linux e ele estava interpretando os caracteres especiais. Consegui resolver colocando a senha entre aspas duplas. Depois o erro voltou, acho que foi o número de tentativas.
